### ISSUE TITLE
Data are missing

### ISSUE THREAD

**Issue by yyxr75** [kaist-avelab/K-Radar#12]
Hi there,

From 1-20, 5_lpc.zip, 7_lpc.zip, 16_lpc.zip, 17_lpc.zip, 20_lpc.zip file size are KB level. I think those files are missing by accident.
Please double check those files.

Thanks

**Comment by woo9904** [comment]
Hi @yyxr75 

I'll reply on their behalf.

Upon checking the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_), it seems there are some issue with the file; we're planning to re-upload the affected part shortly.

Should you require the complete dataset, including the full Tensor data, we suggest a different acquisition method.
That is sending the hard disk directly.
We kindly request that you provide us with an external hard disk drive (HDD) with a capacity of 18TB or greater. You can send it through international shipping or purchase it via online platforms like Amazon. This data transfer is strictly non-profit basis and has been utilized by various research institutions and corporations.

If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.

Thank you.

**Comment by ylwhxht** [comment]
> Hi @yyxr75
> 
> I'll reply on their behalf.
> 
> Upon checking the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_), it seems there are some issue with the file; we're planning to re-upload the affected part shortly.
> 
> Should you require the complete dataset, including the full Tensor data, we suggest a different acquisition method. That is sending the hard disk directly. We kindly request that you provide us with an external hard disk drive (HDD) with a capacity of 18TB or greater. You can send it through international shipping or purchase it via online platforms like Amazon. This data transfer is strictly non-profit basis and has been utilized by various research institutions and corporations.
> 
> If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.
> 
> Thank you.

@DongHeePaek @woo9904  17_lpc.zip looks like an error, it seems to have been passed as a meta.zip

**Comment by dIronmanb** [comment]
@ylwhxht We've completed to upload 17_lpc.zip. Please check the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_)
if the .zip file is revised. Thank you.

**Comment by ylwhxht** [comment]
> @ylwhxht We've completed to upload 17_lpc.zip. Please check the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_) if the .zip file is revised. Thank you.

OK, thanks~!
