### ISSUE TITLE
Where is  RTK-GPS data?

### ISSUE THREAD

**Issue by Andy-Cheng** [kaist-avelab/K-Radar#14]
Thanks for the great work!
I wonder where might be the RTK-GPS data.
I couldn't find it in your provided download link.

**Comment by Toytiny** [comment]
Me too! The folder of GPS on google drive is void.

**Comment by DongHeePaek** [comment]
Please refer to [Odometry](https://github.com/kaist-avelab/K-Radar#odometry) section.

Thank you.
