### ISSUE TITLE
Sparse Radar Cube Generation

### ISSUE THREAD

**Issue by DekuLiuTesla** [kaist-avelab/K-Radar#16]
Thank you for your great research and contribution!
I noticed that the RTNH model consumes sparse radar cube, which can be generated from radar_zyx_cube. However, the cfg_RTNH_vanilla.yml is used in kradar_detection_v1_0.py for generation, but this file is not included in the repository. So I'm wondering if the required config file is the same as provided cfg_RTNH.yml. Or if possible, could you provide the detailed setting of cfg_RTNH_vanilla.yml?
Thanks again!

**Comment by woo9904** [comment]
Hello @DekuLiuTesla 

I am responding on their behalf.

Upon directly inquiring about your question, it has been confirmed that you can use the config file as it is uploaded on GitHub.
In other words, you can consider 'cfg_RTNH_vanilla.yml' and 'cfg_RTNH.yml' to be the same!

Thank you.
