### ISSUE TITLE
About Lidar Calibration Parameters

### ISSUE THREAD

**Issue by liululu1** [kaist-avelab/K-Radar#17]
Hi!
Where is the extrinsic matrix between 64-channel Lidar and 128-channel Lidar given in the K-Radar dataset file for coordinate conversion?
Thanks.

**Comment by woo9904** [comment]
Hi, @liululu1.

I'll reply on their behalf.

Regarding the calibration, they plan to reorganize and upload it again for your reference.
Thank you!
