### ISSUE TITLE
NAS is down

### ISSUE THREAD

**Issue by ChrisTwombly** [kaist-avelab/K-Radar#20]
Hi I am trying to download the full dataset today 9/1/2023 and I cannot connect to the NAS.

**Comment by Buckler89** [comment]
Same for me

**Comment by weiyulee** [comment]
same here

**Comment by kathy-lee** [comment]
Same to me. Could you help us please? @DongHeePaek

**Comment by DongHeePaek** [comment]
The issue with the NAS malfunction has been rectified. Kindly verify at your earliest convenience. Thank you for your understanding.
