### ISSUE TITLE
Google cloud data missing 

### ISSUE THREAD

**Issue by Ericwen2001** [kaist-avelab/K-Radar#22]
Hi, Thank you for providing this good dataset.
I noticed that some lidar data are missing from your Google Drive.
For example, 5_lpc.zip 7_lpc.zip, 16_lpc.zip,20_lpc.zip does not contain any point cloud.

**Comment by woo9904** [comment]
Hi, @Ericwen2001. 

I'll reply on their behalf.

Upon checking the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_), it seems there are some issue with the file; we're planning to re-upload the affected part shortly.

Should you require the complete dataset, including the full Tensor data, we suggest a different acquisition method.
That is sending the hard disk directly.
We kindly request that you provide us with an external hard disk drive (HDD) with a capacity of 18TB or greater. You can send it through international shipping or purchase it via online platforms like Amazon. This data transfer is strictly non-profit basis and has been utilized by various research institutions and corporations.

If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.

Thank you.

**Comment by Ericwen2001** [comment]
Hi, any updates on the lidar zip reuploading?

**Comment by woo9904** [comment]
@Ericwen2001 
Thanks for reminding me. I uploaded missing parts.
