### ISSUE TITLE
Lisence

### ISSUE THREAD

**Issue by L-Reichardt** [kaist-avelab/K-Radar#26]
What Lisence is the dataset released under? Is it available for commerical use?

**Comment by DongHeePaek** [comment]
As we noted in Section A.4, 'License,' in 'https://arxiv.org/pdf/2206.08171.pdf', the K-Radar dataset is under a CC BY-NC-ND License, which includes Attribution (BY), Non-Commercial (NC), and No Derivatives (ND). Therefore, commercial use of this dataset is not possible.

Thank you.
