### ISSUE TITLE
Unable to build packages for OpenPCDet operations

### ISSUE THREAD

**Issue by DevankGarg** [kaist-avelab/K-Radar#30]
Hello,

First of all, thank you for providing such a good-quality dataset. I was trying to evaluate one of the pre-trained models, so I followed the steps in the detection readme, so on step 7 I am unable to build the OpenPCDet package.

Can you please help

Traceback (most recent call last):
  File "D:\4D RADAR\K-RADAR\K-Radar\radar\lib\site-packages\torch\utils\cpp_extension.py", line 1740, in _run_ninja_build
    subprocess.run(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

**Comment by woo9904** [comment]
It looks like the issue related to incorrect path set for CUDA_HOME. Could you please check by running the following commands?

```bash
$ nvcc -V
$ echo $CUDA_HOME
```

If the CUDA version displayed from these commands does not match, try the following steps to set the desired CUDA version. For instance, if you want to use CUDA version 11.3, you can do the following:

```bash
$ cd /usr/local
$ sudo rm cuda
$ sudo ln -s cuda-11.3 cuda

$ gedit ~/.bashrc
```

Add the following lines to your `~/.bashrc` file:
```bash
export PATH=$PATH:/usr/local/cuda-11.3/bin
export CUDADIR=/usr/local/cuda-11.3
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.3/lib
```

After saving the changes, reactivate your `~/.bashrc` file by running:
```bash
$ source ~/.bashrc
```
