### ISSUE TITLE
potential issue in d3_box_overlap_kernel

### ISSUE THREAD

**Issue by miaozhang97** [kaist-avelab/K-Radar#36]
Hello, I might find a potential issue in function `d3_box_overlap_kernel` in /utils/kitti_eval/eval.py line 138:
The default setting of `z_center=1.0`, which means the `z_center` should be the bottom(or top). But with my understanding, the annotation of K-radar dataset z vaule is of 3D center rather than bottom center. in that case, the calculation of  `iw = min_z - max_z`  can be incorrect. 
Because the bbox and qbox actually have different offset in z-axis. (gt_height/2 and pred_height/2). Consequently, it will affect the final AP_3D performance. (AP_BEV remains the same).

Please tell me if I understand correctly or not. Looking forward to your reply. Thanks!

**Comment by DongHeePaek** [comment]
Thank you for bringing this matter to our attention. We have thoroughly investigated the issue regarding the `z_center` parameter in the `d3_box_overlap_kernel` function within /utils/kitti_eval/eval.py.
Our investigation confirms that setting `z_center=0.5` is indeed the correct configuration, as the K-radar dataset utilizes 3D center coordinates for its annotations. This has been validated through performance testing in the get_official_result function within pipeline_detection_v1_0.py.
The implementation with `z_center=0.5` yields the following performance improvements:

Sedan 3D AP: Increased from 48.2 to 48.7
Bus or Truck AP: Increased from 34.4 to 36.0

We value your careful analysis that led to this revision.
