### ISSUE TITLE
Some errors about 1_rt.zip and 2_rt.zip

### ISSUE THREAD

**Issue by LucasYang567** [kaist-avelab/K-Radar#4]
As shown in the figure, the following errors occurred when i unzipped 1_rt.zip and 2_rt.zip
![image](https://user-images.githubusercontent.com/125250192/218463770-c76e5f6f-12a2-4d5b-880a-4161fc9384b7.png)

**Comment by woo9904** [comment]
Hello @yanglong2000, 

I'll reply on their behalf.

It seems there was an issue with the file; we're planning to re-upload the affected part shortly.

Should you require the complete dataset, including the full Tensor data, we suggest a different acquisition method. 
Please provide an **external hard drive with at least 18TB capacity.** You can send it through international shipping or purchase it via online platforms like Amazon. This data transfer is strictly **non-profit** basis and has been utilized by various research institutions and corporations.

If you are interested in receiving the full dataset directly on an external HDD, please send an email to @DongHeePaek or me.

Thank you.
