### ISSUE TITLE
The pretrained model is unavailable 

### ISSUE THREAD

**Issue by Nick-Sun1018** [kaist-avelab/K-Radar#6]
We are very appreciate your excellent work, the link of pertained model is unavailable right now, would you please to re upload one? Thank you!

**Comment by woo9904** [comment]
Hi @Nick-Sun1018,

I apologize for the delayed response.

Upon checking the [Google Drive](https://drive.google.com/drive/folders/1IfKu-jKB1InBXmfacjMKQ4qTm8jiHrG_), it seems that the pretrained model is already present. 

Thank you!
